name = "fsc-referral"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "REFERRALS"
id = "REPLACE_WITH_YOUR_KV_NAMESPACE_ID"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "fsc-uploads"
