name = "fsc-referral"
main = "worker.js"
compatibility_date = "2024-01-01"

[[kv_namespaces]]
binding = "REFERRALS"
id = "21f3f83b64554fedb19b22161600451b"

[[r2_buckets]]
binding = "UPLOADS"
bucket_name = "fsc-uploads"
